name: LWJGL Build

on:
  push:
    branches:
      - master

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_PARAMS: --cache-control "public,must-revalidate,proxy-revalidate,max-age=0"
  OPUS_PARAMS: --disable-extra-programs --disable-doc --disable-hardening --disable-stack-protector --enable-custom-modes

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
#         ARCH: [x64, arm32, arm64, mips64]
        ARCH: [powerpc64le]
        include:
          # -----
#           - ARCH: x64
#             PACKAGES:
#             CC:
#             HOST: x86_64-pc-linux-gnu
#             STRIP: strip
          # -----
#           - ARCH: arm32
#             PACKAGES: gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
#             CC: CC=arm-linux-gnueabihf-gcc
#             HOST: arm-unknown-linux-gnueabihf
#             STRIP: arm-linux-gnueabihf-strip
          # -----
#           - ARCH: arm64
#             PACKAGES: gcc-aarch64-linux-gnu libc6-dev-arm64-cross
#             CC: CC=aarch64-linux-gnu-gcc
#             HOST: aarch64-unknown-linux-gnu
#             STRIP: aarch64-linux-gnu-strip
          # -----
#           - ARCH: mips64
#             PACKAGES: gcc-mips64el-linux-gnuabi64 libc6-dev-mips64el-cross
#             CC: CC=mips64el-linux-gnuabi64-gcc
#             HOST: mips64el-unknown-linux-gnu
#             STRIP: mips64el-linux-gnuabi64-strip
          # -----
          - ARCH: powerpc64le
            PACKAGES: gcc-powerpc64le-linux-gnu libc6-dev-ppc64el-cross
            CC: CC=powerpc64le-linux-gnu-gcc
            HOST: powerpc64le-unknown-linux-gnu
            STRIP: powerpc64le-linux-gnu-strip
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - run: |
          sudo apt-get update
          sudo apt-get -yq install ${{matrix.PACKAGES}}
        name: Install dependencies
        if: ${{ matrix.PACKAGES != '' }}
      - run: |
          cd ogg
          ./autogen.sh
          ./configure --host=${{matrix.HOST}}
        name: Configure ogg
      - run: |
          ./autogen.sh
          ${{matrix.CC}} ./configure ${{env.OPUS_PARAMS}} --host=${{matrix.HOST}}
        name: Configure build
      - run: |
          make
          ${{matrix.STRIP}} .libs/libopus.so
        name: Build
      - run: aws s3 cp .libs/libopus.so s3://darren-lwjgl-build/nightly/linux/${{matrix.ARCH}}/ $S3_PARAMS
        name: Upload artifact
#       - run: |
#           git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > libopus.so.git
#           aws s3 cp libopus.so.git s3://lwjgl-build/nightly/linux/${{matrix.ARCH}}/ $S3_PARAMS
#         name: Upload git revision

  
